#!/bin/bash

get_volume() {
    pactl get-sink-volume @DEFAULT_SINK@ \
        | grep -oP '\d+%' | head -1 | tr -d '%'
}

get_mute() {
    pactl get-sink-mute @DEFAULT_SINK@ | grep -q "yes"
}

print_volume() {
    VOL=$(get_volume)
    if get_mute; then
        ICON="󰖁"
        TEXT="Mute"
    else
        ICON="󰕾"
        TEXT="${VOL}%"
    fi
    echo "$ICON $TEXT"
}

case "$BLOCK_BUTTON" in
    1) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    2) pactl set-sink-volume @DEFAULT_SINK@ 50% ;;
    4) pactl set-sink-volume @DEFAULT_SINK@ +5% ;;
    5) pactl set-sink-volume @DEFAULT_SINK@ -5% ;;
esac

print_volume
